patient/force-app/main/default/objects/Contact/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>IF( AND(NOT(ISBLANK( FirstName )),NOT(ISBLANK(Middle_Name__c)),NOT(ISBLANK( LastName ))) , FirstName+&apos; &apos;+Middle_Name__c+&apos; &apos;+LastName , IF(AND(NOT(ISBLANK(FirstName)),NOT(ISBLANK(LastName ))), FirstName+&apos; &apos;+LastName , FirstName))</formula>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Medical Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

patient/force-app/main/default/objects/Patient__c/fields/Admitted_Date__c.field-meta.xml
<CustomField>
    <fullName>Admitted_Date__c</fullName>
    <label>Admitted Date</label>
    <type>DateTime</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Amount_Pending__c.field-meta.xml
<CustomField>
    <fullName>Amount_Pending__c</fullName>
    <label>Amount Pending</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Any_Disability__c.field-meta.xml
<CustomField>
    <fullName>Any_Disability__c</fullName>
    <label>Any Disability</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Any_Health_History_Related_Information__c.field-meta.xml
<CustomField>
    <fullName>Any_Health_History_Related_Information__c</fullName>
    <label>Any Health History Related Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Any_other_Information__c.field-meta.xml
<CustomField>
    <fullName>Any_other_Information__c</fullName>
    <label>Any other Information</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Billing_Status__c.field-meta.xml
<CustomField>
    <fullName>Billing_Status__c</fullName>
    <label>Billing Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Paid</fullName>
            </value>
            <value>
                <fullName>Waived off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dublin</fullName>
            </value>
            <value>
                <fullName>Cork</fullName>
            </value>
            <value>
                <fullName>Limerick</fullName>
            </value>
            <value>
                <fullName>Galway</fullName>
            </value>
            <value>
                <fullName>Waterford</fullName>
            </value>
            <value>
                <fullName>Drogheda</fullName>
            </value>
            <value>
                <fullName>Kilkenny</fullName>
            </value>
            <value>
                <fullName>Wexford</fullName>
            </value>
            <value>
                <fullName>Sligo</fullName>
            </value>
            <value>
                <fullName>Clonmel</fullName>
            </value>
            <value>
                <fullName>Dundalk</fullName>
            </value>
            <value>
                <fullName>Bray</fullName>
            </value>
            <value>
                <fullName>Navan (An Uaimh)</fullName>
            </value>
            <value>
                <fullName>Ennis</fullName>
            </value>
            <value>
                <fullName>Tralee</fullName>
            </value>
            <value>
                <fullName>Carlow</fullName>
            </value>
            <value>
                <fullName>Naas</fullName>
            </value>
            <value>
                <fullName>Athlone</fullName>
            </value>
            <value>
                <fullName>Letterkenny</fullName>
            </value>
            <value>
                <fullName>Tullamore</fullName>
            </value>
            <value>
                <fullName>Killarney</fullName>
            </value>
            <value>
                <fullName>Arklow</fullName>
            </value>
            <value>
                <fullName>Cobh</fullName>
            </value>
            <value>
                <fullName>Castlebar</fullName>
            </value>
            <value>
                <fullName>Midleton</fullName>
            </value>
            <value>
                <fullName>Mallow</fullName>
            </value>
            <value>
                <fullName>Ballina</fullName>
            </value>
            <value>
                <fullName>Enniscorthy</fullName>
            </value>
            <value>
                <fullName>Wicklow</fullName>
            </value>
            <value>
                <fullName>Cavan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dublin</fullName>
            </value>
            <value>
                <fullName>Cork</fullName>
            </value>
            <value>
                <fullName>Limerick</fullName>
            </value>
            <value>
                <fullName>Galway</fullName>
            </value>
            <value>
                <fullName>Waterford</fullName>
            </value>
            <value>
                <fullName>Louth</fullName>
            </value>
            <value>
                <fullName>Kilkenny</fullName>
            </value>
            <value>
                <fullName>Wexford</fullName>
            </value>
            <value>
                <fullName>Sligo</fullName>
            </value>
            <value>
                <fullName>Tipperary</fullName>
            </value>
            <value>
                <fullName>Wicklow</fullName>
            </value>
            <value>
                <fullName>Meath</fullName>
            </value>
            <value>
                <fullName>Clare</fullName>
            </value>
            <value>
                <fullName>Kerry</fullName>
            </value>
            <value>
                <fullName>Carlow</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>Westmeath</fullName>
            </value>
            <value>
                <fullName>Donegal</fullName>
            </value>
            <value>
                <fullName>Offaly</fullName>
            </value>
            <value>
                <fullName>Mayo</fullName>
            </value>
            <value>
                <fullName>Cavan</fullName>
            </value>
            <value>
                <fullName>Longford</fullName>
            </value>
            <value>
                <fullName>Monaghan</fullName>
            </value>
            <value>
                <fullName>Laois</fullName>
            </value>
            <value>
                <fullName>Dublin (Fingal)</fullName>
            </value>
            <value>
                <fullName>Roscommon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Death_Date__c.field-meta.xml
<CustomField>
    <fullName>Death_Date__c</fullName>
    <label>Death Date</label>
    <type>DateTime</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Death_Reason__c.field-meta.xml
<CustomField>
    <fullName>Death_Reason__c</fullName>
    <label>Death Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Discharge_Date__c.field-meta.xml
<CustomField>
    <fullName>Discharge_Date__c</fullName>
    <label>Discharge Date</label>
    <type>DateTime</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Do_you_drink__c.field-meta.xml
<CustomField>
    <fullName>Do_you_drink__c</fullName>
    <label>Do you drink?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Do_you_smoke__c.field-meta.xml
<CustomField>
    <fullName>Do_you_smoke__c</fullName>
    <label>Do you smoke?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Not Specified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Doctor_s_Consultation__c.field-meta.xml
<CustomField>
    <fullName>Doctor_s_Consultation__c</fullName>
    <label>Doctor&apos;s Consultation</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Doctor_s_Prescribed_Medicine__c.field-meta.xml
<CustomField>
    <fullName>Doctor_s_Prescribed_Medicine__c</fullName>
    <label>Doctor&apos;s Prescribed Medicine</label>
    <length>131072</length>
    <type>Html</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Enter patient&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <formula>IF(  AND(NOT(ISBLANK(First_Name__c)),NOT(ISBLANK(Middle_Name__c)),NOT(ISBLANK(Last_Name__c)))     , First_Name__c+&apos; &apos;+Middle_Name__c+&apos; &apos;+Last_Name__c,  IF(AND(NOT(ISBLANK(First_Name__c)),NOT(ISBLANK(Last_Name__c))), First_Name__c+&apos; &apos;+Last_Name__c,  First_Name__c ))</formula>
    <label>Full Name</label>
    <type>Text</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Guardian_Address__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Address__c</fullName>
    <label>Guardian Address</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Guardian_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Contact_Number__c</fullName>
    <label>Guardian Contact Number</label>
    <type>Phone</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Guardian_Name__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Name__c</fullName>
    <label>Guardian Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Guardian_Relationship__c.field-meta.xml
<CustomField>
    <fullName>Guardian_Relationship__c</fullName>
    <label>Guardian Relationship</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mother</fullName>
            </value>
            <value>
                <fullName>Father</fullName>
            </value>
            <value>
                <fullName>Grandfather</fullName>
            </value>
            <value>
                <fullName>Grandmother</fullName>
            </value>
            <value>
                <fullName>Brother</fullName>
            </value>
            <value>
                <fullName>Sister</fullName>
            </value>
            <value>
                <fullName>Nephew</fullName>
            </value>
            <value>
                <fullName>Relative</fullName>
            </value>
            <value>
                <fullName>Son</fullName>
            </value>
            <value>
                <fullName>Daughter</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>No Relationship</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Hospital_Name__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Please mention a hospital name if patient comes from another hospital.</inlineHelpText>
    <label>Hospital Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Patients</relationshipLabel>
    <relationshipName>Patients</relationshipName>
    <type>Lookup</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Enter patient&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unmarried</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorce</fullName>
            </value>
            <value>
                <fullName>Widow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/classes/PatientController.cls
public without sharing class PatientController {
	 @AuraEnabled
    public static list<Patient__c> getPatientRecordsBySearchKey(string searchOpted, string searchKey) {
        list<Patient__c> patientListRecord = new list<Patient__c>();    
        System.debug('searchOpted : '+searchOpted);
         System.debug('searchKey : '+searchKey);
        if(String.isBlank(searchOpted) ){
			 throw new AuraHandledException('Please Select Search by option..'); 
        }else if(String.isBlank(searchKey)){
             throw new AuraHandledException('Please Enter a '+searchOpted+' value to search..'); 
        }else{
        string searchKeyword = '%' + searchKey + '%';
        
        if(searchOpted == 'Medical Record #'){
            System.debug('Inside Medical Record #');
            patientListRecord = [Select Address_Line_1__c,Address_Line_2__c,Admitted_Date__c,Amount_Paid__c,
                                 Amount_Pending__c,Any_Disability__c,Any_Health_History_Related_Information__c,
                                 Any_other_Information__c,Billing_Status__c,City__c,Contact_Number__c,Country__c,
                                 County__c,CreatedById,CreatedDate,Date_of_Birth__c,Death_Date__c,Death_Reason__c,
                                 Discharge_Date__c,Do_you_drink__c,Do_you_smoke__c,
                                 Doctor_s_Consultation__c,Doctor_s_Prescribed_Medicine__c,Email__c,First_Name__c,
                                 Full_Name__c,Gender__c,Guardian_Address__c,Guardian_Contact_Number__c,
                                 Guardian_Name__c,Guardian_Relationship__c,Hospital_Name__c,Id,IsDeleted,
                                 Last_Name__c,LastActivityDate,LastModifiedById,LastModifiedDate,
                                 LastReferencedDate,LastViewedDate,Marital_Status__c,Middle_Name__c,
                                 Name,New_Patient__c,Next_Appointment_Date__c,Parent_Medical_Record_Number__c,
                                 Patient_need_to_take_any_tests__c,Postal_Code__c,PPS_Number__c,Salutation__c,
                                 Total_Amount__c,Passport_Number__c 
                                 FROM Patient__c
                                 WHERE Name LIKE : searchKeyword];
        }else if(searchOpted == 'Contact Number'){
            System.debug('Inside Contact Number');
            patientListRecord = [Select Address_Line_1__c,Address_Line_2__c,Admitted_Date__c,Amount_Paid__c,
                                 Amount_Pending__c,Any_Disability__c,Any_Health_History_Related_Information__c,
                                 Any_other_Information__c,Billing_Status__c,City__c,Contact_Number__c,Country__c,
                                 County__c,CreatedById,CreatedDate,Date_of_Birth__c,Death_Date__c,Death_Reason__c,
                                 Discharge_Date__c,Do_you_drink__c,Do_you_smoke__c,
                                 Doctor_s_Consultation__c,Doctor_s_Prescribed_Medicine__c,Email__c,First_Name__c,
                                 Full_Name__c,Gender__c,Guardian_Address__c,Guardian_Contact_Number__c,
                                 Guardian_Name__c,Guardian_Relationship__c,Hospital_Name__c,Id,IsDeleted,
                                 Last_Name__c,LastActivityDate,LastModifiedById,LastModifiedDate,
                                 LastReferencedDate,LastViewedDate,Marital_Status__c,Middle_Name__c,
                                 Name,New_Patient__c,Next_Appointment_Date__c,Parent_Medical_Record_Number__c,
                                 Patient_need_to_take_any_tests__c,Postal_Code__c,PPS_Number__c,Salutation__c,
                                 Total_Amount__c,Passport_Number__c 
                                 FROM Patient__c
                                 WHERE Contact_Number__c LIKE : searchKeyword];
        }else if(searchOpted == 'PPS Number'){
            System.debug('Inside PPS Number');
            patientListRecord = [Select Address_Line_1__c,Address_Line_2__c,Admitted_Date__c,Amount_Paid__c,
                                 Amount_Pending__c,Any_Disability__c,Any_Health_History_Related_Information__c,
                                 Any_other_Information__c,Billing_Status__c,City__c,Contact_Number__c,Country__c,
                                 County__c,CreatedById,CreatedDate,Date_of_Birth__c,Death_Date__c,Death_Reason__c,
                                 Discharge_Date__c,Do_you_drink__c,Do_you_smoke__c,
                                 Doctor_s_Consultation__c,Doctor_s_Prescribed_Medicine__c,Email__c,First_Name__c,
                                 Full_Name__c,Gender__c,Guardian_Address__c,Guardian_Contact_Number__c,
                                 Guardian_Name__c,Guardian_Relationship__c,Hospital_Name__c,Id,IsDeleted,
                                 Last_Name__c,LastActivityDate,LastModifiedById,LastModifiedDate,
                                 LastReferencedDate,LastViewedDate,Marital_Status__c,Middle_Name__c,
                                 Name,New_Patient__c,Next_Appointment_Date__c,Parent_Medical_Record_Number__c,
                                 Patient_need_to_take_any_tests__c,Postal_Code__c,PPS_Number__c,Salutation__c,
                                 Total_Amount__c,Passport_Number__c 
                                 FROM Patient__c
                                 WHERE PPS_Number__c LIKE : searchKeyword];
        }else{
            System.debug('Inside Name');
            patientListRecord = [Select Address_Line_1__c,Address_Line_2__c,Admitted_Date__c,Amount_Paid__c,
                                 Amount_Pending__c,Any_Disability__c,Any_Health_History_Related_Information__c,
                                 Any_other_Information__c,Billing_Status__c,City__c,Contact_Number__c,Country__c,
                                 County__c,CreatedById,CreatedDate,Date_of_Birth__c,Death_Date__c,Death_Reason__c,
                                 Discharge_Date__c,Do_you_drink__c,Do_you_smoke__c,
                                 Doctor_s_Consultation__c,Doctor_s_Prescribed_Medicine__c,Email__c,First_Name__c,
                                 Full_Name__c,Gender__c,Guardian_Address__c,Guardian_Contact_Number__c,
                                 Guardian_Name__c,Guardian_Relationship__c,Hospital_Name__c,Id,IsDeleted,
                                 Last_Name__c,LastActivityDate,LastModifiedById,LastModifiedDate,
                                 LastReferencedDate,LastViewedDate,Marital_Status__c,Middle_Name__c,
                                 Name,New_Patient__c,Next_Appointment_Date__c,Parent_Medical_Record_Number__c,
                                 Patient_need_to_take_any_tests__c,Postal_Code__c,PPS_Number__c,Salutation__c,
                                 Total_Amount__c,Passport_Number__c 
                                 FROM Patient__c
                                 WHERE Full_Name__c LIKE : searchKeyword];
        }
       
         if(patientListRecord.size() == 0){
            throw new AuraHandledException('No Patient Records Found..'); 
         }
        }
        System.debug('searchKey : '+patientListRecord);
        return patientListRecord;
    }
    @AuraEnabled
    public static String getPatientIdByPPSN(string ppsnumber) {
        String patientId = '';
         System.debug('ppsnumber : '+ppsnumber);
        if(String.isBlank(ppsnumber) ){
			 throw new AuraHandledException('Please Enter valid PPS Number..'); 
        }else{
			patientId = [Select Id FROM Patient__c WHERE PPS_Number__c =: ppsnumber Limit 1].Id;
        }
        System.debug('patientId : '+patientId);
        return patientId;
    }
    
    @AuraEnabled
    public static Boolean validateReceptionist() {
        Boolean isReceptionist = false;
        String userId = UserInfo.getUserId();
        System.debug('userId : '+userId);
        User usr = [Select Id,FederationIdentifier FROM USER WHere Id=:userId];
         System.debug('usr : '+usr);
        if(usr != null && String.isNotBlank(usr.FederationIdentifier) && usr.FederationIdentifier.StartsWith('Receptionist_')){
			 isReceptionist = true;
        }
        System.debug('isReceptionist : '+isReceptionist);
        return isReceptionist;
    }
}