patient/force-app/main/default/objects/Patient__c/Patient__c.object-meta.xml
<CustomObject>
    <label>Patient</label>
    <nameField>
        <displayFormat>PN-{00000}</displayFormat>
        <label>Medical Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

patient/force-app/main/default/objects/Patient__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Dublin</fullName>
            </value>
            <value>
                <fullName>Cork</fullName>
            </value>
            <value>
                <fullName>Limerick</fullName>
            </value>
            <value>
                <fullName>Galway</fullName>
            </value>
            <value>
                <fullName>Waterford</fullName>
            </value>
            <value>
                <fullName>Drogheda</fullName>
            </value>
            <value>
                <fullName>Kilkenny</fullName>
            </value>
            <value>
                <fullName>Wexford</fullName>
            </value>
            <value>
                <fullName>Sligo</fullName>
            </value>
            <value>
                <fullName>Clonmel</fullName>
            </value>
            <value>
                <fullName>Dundalk</fullName>
            </value>
            <value>
                <fullName>Bray</fullName>
            </value>
            <value>
                <fullName>Navan (An Uaimh)</fullName>
            </value>
            <value>
                <fullName>Ennis</fullName>
            </value>
            <value>
                <fullName>Tralee</fullName>
            </value>
            <value>
                <fullName>Carlow</fullName>
            </value>
            <value>
                <fullName>Naas</fullName>
            </value>
            <value>
                <fullName>Athlone</fullName>
            </value>
            <value>
                <fullName>Letterkenny</fullName>
            </value>
            <value>
                <fullName>Tullamore</fullName>
            </value>
            <value>
                <fullName>Killarney</fullName>
            </value>
            <value>
                <fullName>Arklow</fullName>
            </value>
            <value>
                <fullName>Cobh</fullName>
            </value>
            <value>
                <fullName>Castlebar</fullName>
            </value>
            <value>
                <fullName>Midleton</fullName>
            </value>
            <value>
                <fullName>Mallow</fullName>
            </value>
            <value>
                <fullName>Ballina</fullName>
            </value>
            <value>
                <fullName>Enniscorthy</fullName>
            </value>
            <value>
                <fullName>Wicklow</fullName>
            </value>
            <value>
                <fullName>Cavan</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <label>County</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Dublin</fullName>
            </value>
            <value>
                <fullName>Cork</fullName>
            </value>
            <value>
                <fullName>Limerick</fullName>
            </value>
            <value>
                <fullName>Galway</fullName>
            </value>
            <value>
                <fullName>Waterford</fullName>
            </value>
            <value>
                <fullName>Louth</fullName>
            </value>
            <value>
                <fullName>Kilkenny</fullName>
            </value>
            <value>
                <fullName>Wexford</fullName>
            </value>
            <value>
                <fullName>Sligo</fullName>
            </value>
            <value>
                <fullName>Tipperary</fullName>
            </value>
            <value>
                <fullName>Wicklow</fullName>
            </value>
            <value>
                <fullName>Meath</fullName>
            </value>
            <value>
                <fullName>Clare</fullName>
            </value>
            <value>
                <fullName>Kerry</fullName>
            </value>
            <value>
                <fullName>Carlow</fullName>
            </value>
            <value>
                <fullName>Kildare</fullName>
            </value>
            <value>
                <fullName>Westmeath</fullName>
            </value>
            <value>
                <fullName>Donegal</fullName>
            </value>
            <value>
                <fullName>Offaly</fullName>
            </value>
            <value>
                <fullName>Mayo</fullName>
            </value>
            <value>
                <fullName>Cavan</fullName>
            </value>
            <value>
                <fullName>Longford</fullName>
            </value>
            <value>
                <fullName>Monaghan</fullName>
            </value>
            <value>
                <fullName>Laois</fullName>
            </value>
            <value>
                <fullName>Dublin (Fingal)</fullName>
            </value>
            <value>
                <fullName>Roscommon</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <inlineHelpText>Enter patient&apos;s first name</inlineHelpText>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <inlineHelpText>Enter patient&apos;s last name</inlineHelpText>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Marital_Status__c.field-meta.xml
<CustomField>
    <fullName>Marital_Status__c</fullName>
    <label>Marital Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unmarried</fullName>
            </value>
            <value>
                <fullName>Married</fullName>
            </value>
            <value>
                <fullName>Divorce</fullName>
            </value>
            <value>
                <fullName>Widow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Middle_Name__c.field-meta.xml
<CustomField>
    <fullName>Middle_Name__c</fullName>
    <inlineHelpText>Enter patient&apos;s middle name</inlineHelpText>
    <label>Middle Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Passport_Number__c.field-meta.xml
<CustomField>
    <fullName>Passport_Number__c</fullName>
    <externalId>true</externalId>
    <label>Passport Number</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/PPS_Number__c.field-meta.xml
<CustomField>
    <fullName>PPS_Number__c</fullName>
    <externalId>true</externalId>
    <label>PPS Number</label>
    <length>9</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

patient/force-app/main/default/objects/Patient__c/fields/Salutation__c.field-meta.xml
<CustomField>
    <fullName>Salutation__c</fullName>
    <label>Salutation</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mr.</fullName>
            </value>
            <value>
                <fullName>Mrs.</fullName>
            </value>
            <value>
                <fullName>Miss.</fullName>
            </value>
            <value>
                <fullName>Dr.</fullName>
            </value>
            <value>
                <fullName>Master</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

patient/force-app/main/default/classes/AWStoSFDC.cls
public class AWStoSFDC{

@AuraEnabled
 public static List<Patient__c> callAWS(String PPSNumber) {
    // Name of files in the AWS
    List<String> fileNames = new List<String>{'PatientData'};
	List<Patient__c> patientList = new List<Patient__c>();
    //Get file contents
   
  
   
     //get Patient__c with taking refernce of PPSN field ;
    try{
         patientList = getCSVFileContent(fileNames, PPSNumber);
        system.debug('patientList--->'+patientList);

		 if(patientList.isEmpty()){
            throw new AuraHandledException('No Patient Records Found with '+PPSNumber); 
         }
            
    }Catch(DMLException de){
         System.debug('GetError---->'+de);
         return patientList;
     }
     return patientList;
 }

//Get file contents via HTTP Request
public static List<Patient__c> getCSVFileContent(list<string> fileNames, String PPSNumber) {
List<Patient__c> patientList = new List<Patient__c>();
    Http http = new Http();    
    HttpRequest request = new HttpRequest();
    FileMapping fileMapping = new FileMapping();
    for(String fileName : fileNames){
          
        // Set the request parameter
        setSetRequestParams(request, fileName);       
        HttpResponse response = http.send(request);
        // Parse the JSON response
        if (response.getStatusCode() != 201) {
            System.debug('response'+response.getBody());
            System.debug('The status code returned was not expected: ' +
            response.getStatusCode() + ' ' + response.getStatus());
            patientList = parsePatientResponse(response,PPSNumber);
           
                                 
        } 
        else {
             System.debug(response.getBody());
            }
    }
    return patientList;
}

Public static List<Patient__c> parsePatientResponse(HttpResponse response,String PPSNumber){
    String[] csvFileLines = response.getBody().split('\n'); 
    List<Patient__c> patientlist = new List<Patient__c>();
    try{
        
        for(Integer i=1;i<csvFileLines.size();i++){
            String[] csvRecordData = csvFileLines[i].split(',');
            if(String.isNotBlank(PPSNumber) && String.isNotBlank(csvRecordData[0]) && PPSNumber.equalsIgnoreCase(csvRecordData[0])){
                Patient__c patientObj = new Patient__c() ;
                patientObj.PPS_Number__c = csvRecordData[0];
                patientObj.Salutation__c = csvRecordData[1];             
                patientObj.First_Name__c = csvRecordData[2];
                patientObj.Last_Name__c = csvRecordData[3];
                patientObj.Middle_Name__c = csvRecordData[4]; 
                patientObj.Passport_Number__c = csvRecordData[5];  
                patientObj.Marital_Status__c = csvRecordData[6];
                System.debug('@@csvRecordData[7] : '+csvRecordData[7]);
                patientObj.Date_of_Birth__c = date.parse(csvRecordData[7]);
                patientObj.Address_Line_1__c = csvRecordData[8]; 
                patientObj.Address_Line_2__c = csvRecordData[9];  
                patientObj.County__c = csvRecordData[10];
                patientObj.City__c = csvRecordData[11];
                patientObj.Country__c = csvRecordData[12];
                patientObj.Postal_Code__c = csvRecordData[13]; 
                patientObj.Contact_Number__c = csvRecordData[14];
                patientObj.Email__c = csvRecordData[15] ;
                patientlist.add(patientObj);  
            }
            }
     }
     catch (Exception exp)
     {
         //ApexPages.Message errorMessage = new ApexPages.Message(ApexPages.severity.ERROR,'An error has occured while importin data Please make sure input csv file is correct');
        // ApexPages.addMessage(errorMessage);
        System.debug('Exception occurred : '+exp.getStackTraceString());
        throw new AuraHandledException('Unable to get patient records from AWS..'); 
         
     }

     return patientlist;
}

Public static void setSetRequestParams(HttpRequest request, string fileName){
    //String endPoint = 'callout:AWS/'+fileName+'.csv';
  //  String endPoint = 'callout:AWS/myppsndata/'+fileName+'.csv';
  String endPoint = 'callout:AWS/PatientData.csv';
    System.debug('@@@endPoint : '+endPoint);
    request.setEndpoint(endPoint);
    request.setMethod('GET');
    request.setHeader('Content-Type', 'application/json;charset=UTF-8');
    //request.setHeader('Host', 's3.amazonaws.com/myppsndata');
    System.debug('@@@request : '+request);
}

  public  class FileMapping{
    public List<Patient__c> patientRecords;
  }


}